language: python
group: edge
python:
  - "2.7"
  - "3.4"
env:
  - EXPLICATES_SETTINGS="../settings_test.py"
addons:
  postgresql: "9.5"
install:
  - pip install -U pip
  - pip install -r requirements.txt
before_script:
  - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
  - psql -c "create database explicates_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
script:
  - pycodestyle
  - alembic -c alembictest.ini stamp head
  - alembic -c alembictest.ini upgrade head
  - nosetests test/
  - mkdocs build --clean
after_success:
  - pip install coveralls
  - coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/
  on:
    branch: master
