---
- hosts: all
  become: true
  become_method: sudo
  vars:
    explicates_user: "vagrant"
    explicates_path: "/vagrant"
    vagrant_home: "/home/vagrant"
    virtualenv_path: "/home/vagrant/explicates-env"

  tasks:
    - name: Check Ubuntu 18.04 running
      assert:
        that:
          - ansible_distribution == 'Ubuntu'
          - ansible_distribution_release == 'bionic'

    - name: update apt cache
      apt: update_cache=yes

    - name: install Python
      apt: name={{item}} state=latest
      with_items:
        - python
        - python-dev
        - python-virtualenv
        - python-setuptools
        - python-pip

    - name: upgrade pip
      become_user: "{{explicates_user}}"
      pip: name=pip state=latest chdir={{explicates_path}} virtualenv={{virtualenv_path}} virtualenv_site_packages=yes

    - name: install Explicates virtualenv packages
      become_user: "{{explicates_user}}"
      pip: chdir={{explicates_path}} requirements={{explicates_path}}/requirements.txt virtualenv={{virtualenv_path}} virtualenv_site_packages=yes

    - name: check alembic.ini exists
      stat: path={{explicates_path}}/alembic.ini
      register: check_alembic

    - name: copy alembic template when it does not exist
      command: cp -p {{explicates_path}}/alembic.ini.tmpl {{explicates_path}}/alembic.ini
      when: not check_alembic.stat.exists

    - name: check settings.py exists
      stat: path={{explicates_path}}/settings.py
      register: check_settings

    - name: copy settings template when it does not exist
      command: cp -p {{explicates_path}}/settings.py.tmpl {{explicates_path}}/settings.py
      when: not check_settings.stat.exists

    - name: install PostgreSQL
      apt: name={{item}} state=latest
      with_items:
        - postgresql
        - postgresql-server-dev-all
        - libpq-dev
        - python-psycopg2

    - name: start PostgreSQL service
      service: name=postgresql state=started

    # http://stackoverflow.com/a/16783253
    # psql -lqt | cut -d \| -f 1 | grep -w <db_name>
    - name: check if DB already exists
      become_user: postgres
      shell: "psql -lqt | cut -d \\| -f 1 | grep -w explicates"
      register: explicates_db_exists
      changed_when: False
      failed_when: not (explicates_db_exists.rc == 0 or explicates_db_exists.rc == 1)

    - name: create Explicates DB user
      become_user: postgres
      postgresql_user: name=explicates password=tester encrypted=yes role_attr_flags=CREATEDB,NOSUPERUSER

    - name: create Explicates DB test user
      become_user: postgres
      postgresql_user: name=rtester password=rtester encrypted=yes role_attr_flags=CREATEDB,NOSUPERUSER

    - name: create Explicates DB
      become_user: postgres
      postgresql_db: name=explicates
                     owner=explicates
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     template='template0'

    - name: create Explicates Test DB
      become_user: postgres
      postgresql_db: name=explicates_test
                     owner=rtester
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     template='template0'

    - name: populate Explicates DB
      become_user: "{{explicates_user}}"
      command: "{{virtualenv_path}}/bin/python bin/db_create.py"
      args:
        chdir: "{{explicates_path}}"
      when: explicates_db_exists.rc != 0

    # activate virtualenv always in .bashrc
    - name: virtualenv usage by default on bash login
      become_user: "{{explicates_user}}"
      lineinfile:
        dest={{vagrant_home}}/.bashrc
        line=". {{virtualenv_path}}/bin/activate"
        owner=vagrant
        state=present
        insertafter=EOF
        create=yes

    - name: go to /vagrant directory on bash login
      lineinfile:
        dest={{vagrant_home}}/.bashrc
        line="cd {{explicates_path}}"
        owner=vagrant
        state=present
        insertafter=EOF
